package org.computermentors.childdevelopment;

public class Milestones {
    public static String [] headers = new String[]{"Age 0 - 3 months", "Age 3 - 6 months", "Age 6 - 9 months", "Age 9 - 12 months", "Age 12 - 18 Months", "Age 18 - 24 months", "Age 2 - 3 years", "Age 3 - 4 years", "Age 4 - 5 years"};
    public static int[] resourceIds = new int[]{R.drawable.age_0_3_months, R.drawable.age_3_6_months, R.drawable.age_6_9_months, R.drawable.age_9_12_months, R.drawable.age_18_months, R.drawable.age_2_years, R.drawable.age_3_year, R.drawable.age_4_year, R.drawable.age_5_year};
    public static String[] positive = new String[]{"Making cooing sounds to get my attention `Beginning to develop a social smile `Imitating some of my movements and facial expressions `Raising his / her head and chest when lying on his / her stomach `Opening and shutting his / her hands `Holding a rattle or other small toy briefly before dropping it",
            "Respond to his / her own name `Use his / her voice to express joy and displeasure `Transfer objects from one hand to the other `Roll from front to back and back to front `Sit without putting his / her hands down on the ground for support `Show interest in looking at him / herself in the mirror",
            "Babbling `Repeating sequences of sounds over and over `Trying to imitate sounds `Trying to get things that are out of reach `Making noises to show displeasure and satisfaction `Picking up small objects with his / her thumb and finger (pincer grasp) `Show some anxiety when your or another caregiver leaves",
            "Saying 2 or 3 words besides 'mama' and 'dada' `Trying to imitate familiar words `Looking for and finding hidden objects `Sitting without assistance `Pulling him / herself to stand and maybe walking while holding on to furniture `Being shy or anxious around strangers `Repeating sounds or gestures for attention",
            "Walking without help `Holding objects / toys while walking `Turning pages in a book `Using 10 to 20 different words `Understanding the word 'no' `Waving goodbye `Playing games like Pat-A-Cake `Showing a lot of affection `Scribbling with a crayon",
            "Being able to identify body parts `Having conversations with him / herself, toys, dolls, etc. `Using sentences of 2 to 3 words `Make believe / fantasy play `Running and kicking a ball `Pulling toys behind him / herself while walking `Getting more excited about being around other children `Showing some deviant behavior",
            "Identifying some colors by name `Practicing new words through talking to him / herself `Singing songs `Matching objects in his / her hand to objects in a book `Running easily `Pedaling a Tricycle `Being able to screw and unscrew lids `Imitating others `Beginning to play alone",
            "Identifying different shapes by name `Using sentences of 4 / 5 words `Using past tense correctly `Naming several colors `Being able to count a few numbers `Drawing a person with 2 / 4 body parts `Cooperating with other children `Playing 'mom' or 'dad' `Being more independent",
            "Being able to tell his / her own address `Identifying coins by name `Using past, present, or future tense `Knowing his / her own right and left `Counting 10 or more objects `Being able to draw a person with a body `Showing an understanding of time `Wanting to be like his / her own friends `Being more agreeable to rules",
    };
    public static String[] concerns = new String[]{"Does not notice his / her own hands `Does not visually follow moving objects `Does not smile",
            "Does not reach or grab for things `Cannot support his / her head well `Does not pay attention to new faces",
            "Seems very stiff with tight muscles or very floppy like a rag doll `Does not laugh or make squealing sounds `Does not turn his / her head to locate sounds `Cannot sit with help or roll `Does not seem to enjoy being around people" ,
            "Does not babble `not interested in games like Peek-A-Boo `Does not follow objects with both eyes `Cannot sit when supported `Does not reach for objects `Does not turn head to locate sounds",
            "Does not crawl ` stand when supported `Does not say words `Does not point to objects or pictures `Does not show affection for you or other caregivers `Does not enjoy being around people" ,
            "Does not point to objects or pictures `Does not crawl or walk `Cannot stand with support `Has less than 10 words `Does not use gestures like waving goodbye",
            "Cannot walk `Does not say at least 15 words `Does not use 2 word sentences `Does not follow simple instructions `Cannot push a wheeled toy `Does not imitate actions or words",
            "Has very unclear speech `Cannot copy a circle `Shows no interest in pretend play `Does not understand simple instructions `Has difficulty handling small objects `Falls frequently",
            "Cannot throw a ball overhead `Cannot hold a pencil or crayon correctly `Still is very anxious when you or another caregiver leaves `Ignores or has no interest in other children `Does not engage in pretend / fantasy play `Does not use sentences of more than three words",
            "Acts extremely fearful or timid `Is unable to separate from you or another caregiver `Refuses to respond to people `Does not express a wide range of emotion `Cannot give first and last name `Cannot do self-care skills like brushing teeth or washing / drying hands",
    };
}
